// <auto-generated />
using System;
using KioskRewards.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KioskRewards.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    partial class LoyaltyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("KioskRewards.Domain.Entities.PointsAccount", b =>
                {
                    b.Property<Guid>("MemberKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberKey");

                    b.ToTable("PointsAccounts", (string)null);
                });

            modelBuilder.Entity("KioskRewards.Domain.Entities.PointsTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberKey", "CreatedUtc");

                    b.ToTable("PointsTransactions", (string)null);
                });

            modelBuilder.Entity("KioskRewards.Domain.Entities.PointsTransaction", b =>
                {
                    b.HasOne("KioskRewards.Domain.Entities.PointsAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("MemberKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KioskRewards.Domain.Entities.PointsAccount", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
